import '@/styles/global.css'
import { DefaultLayout } from '@/layouts/default'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default DefaultLayout
