import '@/styles/global.css'
import type { ReactNode } from 'react'
import { IconCirclePlus, IconListCheck, IconSettingsFilled } from '@tabler/icons-react'

import { inter } from '@/styles/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout = ({ children }: { children: ReactNode }) => (
  <div className={inter.className}>
    {children}
    <div className='btm-nav'>
      <button className='text-primary' type='button'>
        <IconListCheck />
      </button>
      <button className='active' type='button'>
        <IconCirclePlus />
      </button>
      <button type='button'>
        <IconSettingsFilled />
      </button>
    </div>
  </div>
)

export default Layout
